# -*- coding: utf-8 -*-
"""AI_Task_Srishti.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15WW_khZVI6gKMGiVuLmvAYaZRqf_UR2N
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import easyocr
# import openpyxl
# from PIL import Image
# 
# st.title("Electricity Bill Automation")
# 
# uploaded_file = st.file_uploader("Upload Bill Image", type=["jpg","jpeg","png"])
# 
# if uploaded_file:
# 
#     image = Image.open(uploaded_file)
#     image.save("bill.jpg")
# 
#     st.image(image)
# 
#     reader = easyocr.Reader(['en'])
# 
#     results = reader.readtext("bill.jpg")
# 
#     extracted_text = ""
# 
#     for r in results:
#         extracted_text += r[1] + " "
# 
#     st.subheader("Extracted Text")
#     st.write(extracted_text)
# 
#     wb = openpyxl.load_workbook("/content/Copy of Pranay HOME E-Bill Analysis (6).xlsx")
# 
#     sheet = wb.active
# 
#     sheet["B5"] = "187"
#     sheet["B6"] = "6"
# 
#     output_file = "Final_Output.xlsx"
# 
#     wb.save(output_file)
# 
#     with open(output_file, "rb") as f:
#         st.download_button(
#             "Download Final Excel",
#             f,
#             file_name=output_file
#         )
